---
title: "MetFileAnalysis"
author: "edmar.teixeira@me.com"
date: "Friday, March 27, 2015"
output: html_document
---

## Reads met files from apsim (based on MapOutApsimFiles.R)
## Creates a dataframe with column row

```{r Libs, echo = FALSE, include=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(gridExtra)
```

## The weather file

> That's how the data looks like

```{r DirSet, echo=FALSE}

#Set paths
metFolder <- "C:\\GitHubRepos\\2017_FodderBeetOats\\FodderBeatOats\\"

# Get file
metFile <- read.table(paste0(metFolder,"lincolnPred.met"), skip = 6, header = TRUE, comment.char = "(", blank.lines.skip = TRUE)
head(metFile)

```

```{r}
summary(metFile)
```

# Graph historical averages

> Daily temperaure and radiation

> Monthly rainfall

> Pooled for 30 years

```{r GraphMet, echo = FALSE}

metFile <- data.table(metFile)

fontSize <- 15

# maxt
g1 <- metFile %>%
  filter(year %in% 2014:2018) %>%
  group_by(day) %>%
 # summarise_all(funs(mean)) %>%
  ggplot(aes(x=day, y=maxt))  +
  geom_point(colour= "darkblue", alpha=0.2) +
  stat_smooth(level = 0.9, size = 1, colour="white") + 
  theme_bw() +
 xlab("Day of the year (1-365)") + 
  ylab("Daily maximum temperature (oC)") +
  theme(text = element_text(size=fontSize))

#mint
g2 <- metFile %>%
  filter(year %in% 2014:2018) %>%
  group_by(day) %>%
 # summarise_all(funs(mean)) %>%
  ggplot(aes(x=day, y=mint))  +
  geom_point(colour= "darkblue", alpha=0.2) +
  stat_smooth(level = 0.9, size = 1, colour="white") + 
  theme_bw() +
 xlab("Day of the year (1-365)") + 
  ylab("Daily minimum temperature (oC)") +
  theme(text = element_text(size=fontSize))

#radn
g3 <- metFile %>%
  filter(year %in% 2014:2018) %>%
  group_by(day) %>%
 # summarise_all(funs(mean)) %>%
  ggplot(aes(x=day, y=radn))  +
  geom_point(colour= "darkblue", alpha=0.2) +
  stat_smooth(level = 0.9, size = 1, colour="white") + 
 theme_bw() +
  xlab("Day of the year (1-365)") + 
 # ylab("Daily solar radiation (MJ/m2)" ) +
   ylab(expression(Daily~solar~radiation~~"(MJ "*m^"-2"*")")) +
  theme(text = element_text(size=fontSize))

# rain
metFile$month <- with(metFile, strptime(paste(year, day), format="%Y %j")$mon+1)

g4 <- metFile %>%
  filter(year %in% 2014:2018) %>%
  group_by(year, month) %>%
  summarise_all(funs(sum)) %>%
  group_by(month) %>%
  select(month, rain) %>%
  summarise(rainMean = mean(rain), rainSd = sd(rain)/2) %>%
  ggplot(aes(x=month, y=rainMean)) + 
  geom_bar(stat ='identity') +
  theme_bw() +
 xlab("Month") + 
  ylab("Monthly rainfall (mm)") +
  scale_x_continuous(breaks=1:12) +
  geom_errorbar(aes(ymax = rainMean + rainSd, ymin=rainMean - rainSd), 
                position=position_dodge(width=0.9), width=0.25)+
  theme(text = element_text(size=fontSize))


grid.arrange(g1, g2, g3, g4)
# Save
# ggsave(file="Fig_weather.tiff", dpi = 300)


```

```{r PotEvap_graph}

# Get file (simulated eo by APSIM - Pot ET for modsim paper)
# theFile <- "C:\\Apsim_dev\\Projects\\Forage_MBIE(FRNL)\\ModelStudies\\05_CoverCropPaperSoils\\LightSoil EarlyCover ETPdaily.out"
# 
# etpFile <- read.table(theFile, skip = 3, header = TRUE, comment.char = "(", blank.lines.skip = TRUE)
# head(etpFile)
# tail(etpFile)
# summary(etpFile)


#etpFile$Date <- as.Date(etpFile$Dat, format="%dd-%mm-%YYYY")

#etpFile$day <- yday(etpFile$Date)

#write.csv(etpFile, file = "test.csv")

summary(etpFile)

g5 <- etpFile %>%
  filter(year %in% 2014:2018) %>%
   group_by(day_of_year) %>%
 # summarise_all(funs(mean)) %>%
  ggplot(aes(x=day_of_year, y=eo))  +
  geom_point(colour= "darkblue", alpha=0.2) +
  stat_smooth(level = 0.9, size = 1, colour="white") + 
  xlab("Day of the year (1-365)") + 
  ylab("Potential evapo-transpiration (mm)") +
  theme(text = element_text(size=fontSize))


# g5 <- etpFile %>%
#   filter(year %in% 2014:2018) %>%
#   group_by(year, month) %>%
#   summarise_all(funs(sum)) %>%
#   group_by(month) %>%
#   select(month, eo) %>%
#   summarise(rainMean = mean(eo), rainSd = sd(eo)/2) %>%
#   ggplot(aes(x=month, y=rainMean)) + 
#   geom_bar(stat ='identity') +
#   xlab("Month") + 
#   ylab("Potential evapo-transpiration (mm)") +
#   scale_x_continuous(breaks=1:12) +
#   geom_errorbar(aes(ymax = rainMean + rainSd, ymin=rainMean - rainSd), 
#                 position=position_dodge(width=0.9), width=0.25)+
#   theme(text = element_text(size=fontSize))

grid.arrange(g1, g3, g4, g5)

```


