---
title: "R Notebook"
output: html_notebook
---

```{r, warning=FALSE}
library(RSQLite) # taking care of databases
library(lubridate) # taking care of dates
library(ggplot2)
library(dplyr)
library(tidyr)
library(xlsx)
```

## Load simulated

- this will read simulated data from ApsimX database file

```{r}
# create function to read data (Justin's script from CSIRO)
# this func reads databases now
GetApsimNGTable <- function(dbLoc, table) 
{
  connection <- dbConnect(SQLite(), dbname = dbLoc, flags = SQLITE_RW)
  table <- dbReadTable(connection, table, row.names=NULL)
  dbDisconnect(connection)
  return(table)
}
```

# load address of db
```{r}
# FIXME: APSIM will run in powerPlant in the future but we have to run locally at the moment
db.address <- "C:/GitHubRepos/2017_FodderBeetOats/FodderBeatOats"
db.name <- "/FodderBeetOats.db"
db.full.path <- paste0(db.address,db.name)
```

# check what's inside db
```{r}
con <- dbConnect(SQLite(), dbname = db.full.path, flags = SQLITE_RW)
alltables <- dbListTables(con)
alltables
dbDisconnect(con)
```

# Read db and make df

```{r}

# set table to be retrieved
tableName <- "FRNLReport" # 

# load table into an object
myDbTable <- GetApsimNGTable(db.full.path,tableName)

# make it a dataframe
df <- as.data.frame(myDbTable)

# change date to corerct format 
df$Clock.Today <- ymd_hms(df$Clock.Today)


# Sort out factors
df$Nit <- as.factor(df$Nit)
df$Irr <- as.factor(df$Irr)
df$CropOper.Script.CropSown <- factor(df$CropOper.Script.CropSown )

# get rid of points in column names
#colnames(df) <- gsub("\\.", "", colnames(df))
colnames(df)
```

# explore the df
```{r}
str(df)
```

```{r}
head(df)
```

```{r}
summary(df)
```


```{r}


# get sim names (different table in db)
simNameDf <- as.data.frame (GetApsimNGTable(db.full.path,"Simulations"))

# merge names
myDb <- merge(df, simNameDf, by.x= c("SimulationID"), by.y= c("ID")) 

# Sort out simulation name as factor
myDb$SimName <- factor(myDb$Name)
myDb$Name <- NULL

summary(myDb)
```
## Quick check

- look at leaf biomass

```{r}
myDb %>%
#  select_if(grepl("DM"), names(.))) %>% # FIXME: was trying to summ all biomass variables
  ggplot(aes(x=Clock.Today,y=(FodderBeet.Leaf.Live.Wt+Oats.Leaf.Live.Wt),colour=Irr, linetype=Nit)) +
  geom_line() +
  ylab("g/m2")
  
```

## Save simulated data

- For analysis
```{r}
pathFolderWork <- "K:/Rainshelter/Fodderbeet 2016-2017/Analysis" # FIXME: Send to powerPlant or need to run APSIM-X there?

write.csv(myDb, paste0(pathFolderWork,"/SimulatedDataWorked.csv"), row.names = FALSE) 
```

```{r}
# save power Plant
# pathPowerPlant <- "http://storage.powerplant.pfr.co.nz/workspace/cflmss/MultiCropRotation_APSIM_X/Fodderbeet2016_2017/"
# 
# write.csv(myDb, paste0(pathPowerPlant,"/SimulatedDataWorked.csv"), row.names = FALSE)

# can only open URLs for reading
```

